dev:
  portfolio_monitor:
    cis:
      pgp_key: test_key

test:
  portfolio_monitor:
    cis:
      pgp_key: test_key
    symmetric_encryption:
      key: QUJDREVGMTIzNDU2Nzg5MEFCQ0RFRjEyMzQ1Njc4OTA=
      iv: QUJDREVGMTIzNDU2Nzg5MA==
      version: 2
      previous_key:
        key: key1
        iv: iv1
        version: 1

other_application:
  symmetric_encryption:
    version:    3
    __import__: /test/portfolio_monitor/symmetric_encryption
    iv:         MTIzNDU2Nzg5MEFCQ0RFRg==
    previous_key:
      key:     key0