name: Secret Config CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: elixir:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test